#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars
env

sed -i -e "s|listen_address: localhost|listen_address: `hostname -i`|" /cassandra/conf/cassandra.yaml
sed -i -e "s|rpc_address: localhost|rpc_address: `hostname -i`|" /cassandra/conf/cassandra.yaml
sed -i -e "s|seeds: \"127.0.0.1\"|seeds: \"`hostname -i`\"|" /cassandra/conf/cassandra.yaml

exec 2>&1
exec /cassandra/bin/cassandra -f
